#include "colors.h"

char *g_term_colors[TERM_COLOR_COUNT] = {
  FG_BLACK, FG_RED, FG_GREEN, FG_YELLOW, FG_BLUE, FG_MAGENTA,
  FG_CYAN, FG_WHITE, FG_IBLACK, FG_IRED, FG_IGREEN, FG_IYELLOW,
  FG_IBLUE, FG_IMAGENTA, FG_ICYAN, FG_IWHITE,
  BG_BLACK, BG_RED, BG_GREEN, BG_YELLOW, BG_BLUE, BG_MAGENTA,
  BG_CYAN, BG_WHITE, BG_IBLACK, BG_IRED, BG_IGREEN, BG_IYELLOW,
  BG_IBLUE, BG_IMAGENTA, BG_ICYAN, BG_IWHITE
};
